#!/usr/bin/env bash

# Created: 2016-12-16
# Author: jongbin

CREDPATH="$HOME/creds"
OCPID=$(pidof openconnect)

if [[ $OCPID == "" ]]; then
  if [[ -r $CREDPATH ]]; then
    # shellcheck source=/home/jongbin/creds
    source "$CREDPATH"
    KEY=$(yubioath show "stanford" | awk '{print $NF}')
    sudo echo -e "$SU\n$KEY" | sudo openconnect -b \
      --user=jongbin \
      --passwd-on-stdin \
      --authgroup=Full \
      https://su-vpn.stanford.edu
  else
    echo "Automate password input by declaring variable \$SU in credential file ($CREDPATH)"
    sudo openconnect -b \
      --user=jongbin \
      --authgroup=Full \
      https://su-vpn.stanford.edu
  fi
echo -e "Connection running in background. Stop with suvpndown"
else
  echo "Already connected with PID $OCPID"
  exit 1
fi

