#!/usr/bin/env bash

# Created: 2016-12-16
# Author: jongbin

CREDPATH="$PWD/creds"
OCPID=$(pidof openconnect)

if [[ $OCPID == "" ]]; then
  if [[ -r creds ]]; then
    # shellcheck source=creds
    source $CREDPATH
    KEY=$(yubioath show "stanford" | awk '{print $NF}')
    sudo echo -e "$VPNPASS\n$KEY" | sudo openconnect -b \
      --user=jongbin \
      --passwd-on-stdin \
      --authgroup=Full \
      https://su-vpn.stanford.edu
  else
    echo "Automate password input by declaring variable \$VPNPASS in credential file ($CREDPATH)"
    sudo openconnect -b \
      --user=jongbin \
      --authgroup=Full \
      https://su-vpn.stanford.edu
  fi
echo -e "Connection running in background. Stop with suvpndown"
else
  echo "Already connected with PID $OCPID"
  exit 1
fi

